[profile.default]
libs = ["lib"]
out = "out"
src = "src"

remappings = [
  "v4-core=lib/v4-core",
  "v4-core/=lib/v4-core/",
  "v4-periphery=lib/v4-periphery",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
